services:
  vollev-backend:
    build: ./backend
    container_name: bracket-api
    volumes:
      - database:/app/data
    environment:
      - DB_PATH=/app/data/tournaments.db
    restart: always

  # The Frontend
  volley-frontend:
    build: ./frontend
    container_name: bracket-web
    restart: always

volumes:
  database: