services:
  volley-bracket:
    build:
      context: .
    container_name: volley-manager
    env_file:
      - .env
    environment:
      DB_PATH: /data
    volumes:
      - database:/data
    restart: unless-stopped

volumes:
  database: